application: comshallaazmligo
version: 7
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: controller.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: "2.6"
